### ISSUE TITLE
set ntp configuration on all nodes in all blueprints

### ISSUE THREAD

**Issue by ibenrodriguez** [opnfv/opnfv-ravello-demo#10]
set ntp configuration on all nodes in all blueprints we update or create

server 0.pool.ntp.org
server 1.pool.ntp.org
server 2.pool.ntp.org
server 3.pool.ntp.org

**Comment by ionutbalutoiu** [comment]
`maas` node from the generalized MAAS blueprint has been configured with NTP. The other nodes are empty for this blueprint.

Future blueprints with prebuilt will have NTP configured for other nodes as well.
