### ISSUE TITLE
update maas landing page

### ISSUE THREAD

**Issue by ibenrodriguez** [opnfv/opnfv-ravello-demo#11]
update the maas server apache landing page with the following fixes:

1. redirect to the target page for each service - use a java script to do this as the target pages are on different ports.
1. include default user names and passwords for services like SDN Controller and Horizon and MaaS
1. include link to github repo with some contact info how to make an issue 
1. include link to maas web ui ip:/MAAS ubuntu/ubuntu

**Comment by ionutbalutoiu** [comment]
Updated the landing page for the generalized blueprint with MAAS.

Example of the landing page [here](https://2642a4b0eb47a1e09627f59a4e85104add1df00f.googledrive.com/host/0B2CEI88ASvahfmFwWFpfaGJBM3BxdkpCZGo1MGhBWURib1lJUU9Vd1I4dTJPc3VMMVdJdkE/landing-page.html).

For the prebuilt blueprints, this will be updated with the other endpoints.
