### ISSUE TITLE
upstream JOID changes to OPNFV GERRIT

### ISSUE THREAD

**Issue by ibenrodriguez** [opnfv/opnfv-ravello-demo#12]
We've made some tweaks to the JOID OPNFV Installer to work on Ravello - these need to be upstreamed to the OPNFV Gerrit Repo.

https://gerrit.opnfv.org/gerrit/gitweb?p=joid.git;a=tree;h=refs/heads/master;hb=refs/heads/master

@tyloch Can someone help us with this?

**Comment by ionutbalutoiu** [comment]
Changes to the upstream repo were minimal. Submitted a patch with the commit: https://gerrit.opnfv.org/gerrit/#/c/10835/ to support ravello demo pod.

**Comment by ionutbalutoiu** [comment]
PR merged. Closing this.
