### ISSUE TITLE
tweak disk sizes

### ISSUE THREAD

**Issue by ibenrodriguez** [opnfv/opnfv-ravello-demo#2]
We need to run some tests and investigate the right disk size to use for these VMs.

MaaS - fixed size - more work to adjust - leave as is for now
BootStrap - 50
Controller - 200
Compute - 200

Right now they are 500GB each and some feedback from the community is that it's too much.

**Comment by ionutbalutoiu** [comment]
Tweaked disks sizes for the `bootstrap`, `controller` and `compute` VMs and updated the master MAAS blueprint.
