### ISSUE TITLE
fix network configuration for blueprints

### ISSUE THREAD

**Issue by ibenrodriguez** [opnfv/opnfv-ravello-demo#3]
Today the blueprints we setup on ravello use 3 networks for Public, Private, and Data.
MaaS Private is currently shared with External but should be separated.

1 - MAC Addresses should be assigned statically as per the pattern set in the gliffy drawing.
2 - These need to be changed as so:

- Public: 10.10.0.0/16
- Private: 10.20.0.0/16
- External: 10.30.0.0/16
- Data: 10.40.0.0/16

This means MaaS server will only be used to do the initial PXE boot, DHCP, and DNS - after the openstack is built the machines will use the dedicated external network for access instead of MaaS.

**Current Status**
There are 5 blueprints we are working on:

1. Need to fix first - Pre-built MaaS with empty nodes - ready to build OPNFV with your SDN choice - done - take an hour or two to deploy this blueprint, configure maas then four hours later you can have a working OPNFV setup you can customize. Not self-contained - needs ssh keys, github, edit files. For more advanced developer. - https://cloud.ravellosystems.com/#/0/library/blueprints/67666671/canvas
1. Deployed OPNFV with no SDN OpenStack Tip / Master - pending - easy
1. Deployed OPNFV with ONOS SDN OpenStack Liberty - pending - **see email from Mei Mei**
1. Deployed OPNFV with Juniper OpenContrail SDN OpenStack Juno- done - spin up an app from this blueprint and in 20 minutes you will have a working OpenStack environment. Beginner level. - https://cloud.ravellosystems.com/#/0/library/blueprints/67470930/canvas  **need to redo**
1.  need to redo - Deployed OPNFV with ODL SDN OpenStack Liberty - https://cloud.ravellosystems.com/#/0/library/blueprints/67633711/canvas **need to redo**

**Comment by ionutbalutoiu** [comment]
I've create the 10.30.0.0/16 External dedicated network used by OpenStack VMs. Now the External network is separated from the MAAS private network.

We need to test that VMs have internet access when using the blueprint for a deployment and we can mark this issue as fixed.

**Comment by ibenrodriguez** [comment]
Additional test to prove this is working include: 
1 - login to sdn controller with web ui
2 - login to sdn controller with ssh
3 - login to horizon web ui
4 - login to openstack compute note with ssh
5 - open juju web console ui
6 - ssh to juju admin console
7 - import or list glance images
8 - verify external connectivity for vms on openstack

**Comment by ionutbalutoiu** [comment]
Fixed and tested for both NOSDN and ODL blueprints.
