### ISSUE TITLE
ssh import steps

### ISSUE THREAD

**Issue by ibenrodriguez** [opnfv/opnfv-ravello-demo#4]
ssh import steps

I checked it for you and you can convert you public key pair which is ssh2 format to OpenSSH format with the following command:
ssh-keygen -i -f opnfv-ravello.pub > opnfv-ravello1.pub

**Comment by cnesa** [comment]
I uploaded a new public key in OpenSSH format

**Comment by ibenrodriguez** [comment]
I verified this is resolved.
