### ISSUE TITLE
improve doc version info in blueprint descriptions

### ISSUE THREAD

**Issue by ibenrodriguez** [opnfv/opnfv-ravello-demo#5]

**Comment by tyloch** [comment]
e.g. add Ubuntu version

**Comment by ionutbalutoiu** [comment]
Updated the `OPNVF JOID - Prebuilt MAAS environment` blueprint with verbose description (MAAS version, Ubuntu version, etc).

Future pre-built OPNVF environments that will use this blueprint will contain additional information as needed (OpenContrail version, OpenDaylight version, etc).
