### ISSUE TITLE
can't access web ui for controller and compute nodes

### ISSUE THREAD

**Issue by ibenrodriguez** [opnfv/opnfv-ravello-demo#6]
When JuJu spins up the controller and compute nodes their Web UI are not available from the internet. So we need a way to access these.
@ionutbalutoiu created some IPTABLES NAT rules on the MAAS server but they don't work if the ip addresses change when deployed (like for the OpenStack Horizon dashboard).
Some options...

- use the 4th "EXTERNAL" network for compute and control nodes.
- use VNC to MaaS node with a window manager and firefox web browser
- resolve the iptables issues

On Jan 20, 2016, at 1:23 PM, <Nauman_Ahad@DellTeam.com> <Nauman_Ahad@DellTeam.com> wrote:

Hi Iben,

I got access to the OpenStack dashboard by using the  commands from 
http://linux-ip.net/html/nat-dnat.html

I used the following command on the maas vm:

"sudo iptables -t nat -A PREROUTING -i eth0 -p tcp -d 10.10.0.9 --dport 6090 -j DNAT  --to 10.20.2.152:80"

**Comment by ibenrodriguez** [comment]
# list rules - before making the change to fix nat 

$ sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:6090 to:10.20.1.123:80
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:6080 to:10.20.2.151:80
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:6443 to:10.20.2.151:443
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:http-alt to:10.20.1.115:8080
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:8143 to:10.20.1.115:8143
$ sudo iptables -t nat -A PREROUTING -i eth0 -p tcp -d 10.10.0.9 --dport 6090 -j DNAT --to 10.20.2.152:80
$ sudo iptables -t nat -A PREROUTING -i eth0 -p tcp -d 10.10.0.9 --dport 8143 -j DNAT --to 10.20.2.151:80
$ sudo iptables -t nat -L
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:6090 to:10.20.1.123:80
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:6080 to:10.20.2.151:80
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:6443 to:10.20.2.151:443
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:http-alt to:10.20.1.115:8080
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:8143 to:10.20.1.115:8143
DNAT       tcp  --  anywhere             10.10.0.9            tcp dpt:6090 to:10.20.2.152:80

**Comment by ionutbalutoiu** [comment]
This has been fixed in the current updated NOSDN and ODL blueprints. You need to set the `console-proxy-ip` config of the `nova-cloud-controller` charm to match the MAAS public IP (this differs for every published blueprint).
