### ISSUE TITLE
Floating IP associated with instance not pingable

### ISSUE THREAD

**Issue by Nauman10** [opnfv/opnfv-ravello-demo#8]
I created an Instance and associated a floating IP out of the public pool.

This IP is not pingable, from external machines such as MAAS VM, Control VM.

**Comment by ibenrodriguez** [comment]
I think this was with the contrail blueprint - but please make this a test for any blueprints we make or change.

We can fix this in existing blueprints as we make other changes.

**Comment by ionutbalutoiu** [comment]
Fixed in the NOSDN blueprint. Other blueprints will get fixed as well when updated. Follow instructions from [this](https://docs.google.com/document/d/1ZyMg6yyGAZm-vC29yeKp0_y3EQNaIuEY9JUeJ4dzmGw/edit#heading=h.6349eyaoe9c0) section and get external access for the VMs.
